version: '3.8'

services:
  cml-lancador-socket-server:
    container_name: cml-lancador-socket-server
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: npm run start:dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

